### PR TITLE
fix #13

### LINKED ISSUE #13: App doesn't work on latest Linux Mint
I've used the app on Windows where it works great, but I also wanted to use it on my Linux box. After installing the latest release, I launch it and find it doesn't work. The capture window has a black background.

image

After taking a look, it seems that the version of Electron being used in this project currently doesn't support transparency on my OS. But I did find [this project](https://gitlab.com/doom-fr/electron-transparency-demo) that I was able to quickly run to verify that Electron can do transparency in later versions.

image

So I pulled down the source and started playing around with the Electron version. Currently the version in package.json is 12, and trying all the major versions after 12 I found that version 15 is the minimum version that works with my setup. At the time of writing, the latest version of Electron is 25.

Having solved the transparency issue, I tested the render window, only to find that it isn't getting the capture data from the capture window. Uncommenting the line `mainWindow.webContents.openDevTools();` I was able to discover a runtime error:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'id')
    at selectSource (render.js:37)
    at getVideoSources (render.js:25)
    at async EventEmitter.<anonymous> (render.js:65)
```
After enabling more logging, I was able to determine that the objects returned from `desktopCapturer.getSources({types:["screen"]})` did not have a populated `display_id` property; thus the matching display isn't found in the first parameter of this call:

```js
await selectSource(
    inputSources.filter((is) => is.display_id === display.id.toString())[0],
    display
  );
```

Investigating further, I tried looking at the documentation for `desktopCapturer` and it seems that in the latest Electron version, it is only accessible from the main thread (index.js), not from the browser (render.js). Looking at how it is used in the render.js file, it ultimately only needs to know the `source.id` for the `selectSource` function. Moving some of the code from `render.js` to `index.js`, I was able to finally see the source display ids, detect and handle the error all in the main thread:

```
find display 1881264395124802 @ {"x":0,"y":546,"width":1920,"height":1080}
  screen:430:0, Screen 1: 3803340867
  screen:429:0, Screen 2: 66
(node:33974) UnhandledPromiseRejectionWarning: Error: Cannot find source matching display 1881264395124802. Candidates: [
  {
    "name": "Screen 1",
    "id": "screen:430:0",
    "thumbnail": {
      "isMacTemplateImage": false
    },
    "display_id": "3803340867",
    "appIcon": null
  },
  {
    "name": "Screen 2",
    "id": "screen:429:0",
    "thumbnail": {
      "isMacTemplateImage": false
    },
    "display_id": "66",
    "appIcon": null
  }
]
```

Drat. Looks like the `display.id` and `source.display_id` don't match. This appears to be an Electron bug? (see https://stackoverflow.com/a/66772210). Yup, and here it is (opened way back in 2018, still open) <https://github.com/electron/electron/issues/15111#issuecomment-452346357>. Specifically, one user had a clever workaround to fall back on screen name instead of display id. Added that to my changes in index.js and suddenly I am getting some capture! But it's capturing the wrong screen. I had to go into my display settings and make Screen 1 be my primary monitor (screen 2 was previously set to that) and now it works!

image

I'm going to clean up my changes and submit a PR after I have tested it on Windows and Mac as well (to make sure I haven't broken anything).

### PR DESCRIPTION
**Pull request by joeskeen**
See #13 for details of the problem and the troubleshooting steps I took to arrive at this solution.

* Updated Electron to latest
* Move code that queries video sources into the main thread
* Created a backup method for identifying video source if the `display_id` doesn't match
* Update video source on `"move"` event of capture window (`"moved"` wasn't being called in my environment)

This pull request is a draft until I can test on all platforms:

- [x] Windows
- [x] Mac
- [x] Linux

Testing complete; ready for review!

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -105,21 +105,65 @@ const createWindows = () => {
...
     updateMain(null, captureWindow.getSize())
   );
-  captureWindow.on("move", (event) =>
-    updateMain(captureWindow.getPosition(), null)
-  );
+  captureWindow.on("move", (event) => {
+    updateMain(captureWindow.getPosition(), null);
+    checkWindowBounds(captureWindow);
+    determineScreenToCapture();
+  });
```
Comment (mPyKen) [inline src/index.js:112]: I think calling `determineScreenToCapture()` frequently caused flickering on some systems which is why I moved this to the `moved` event. But it seems this event is [not available on linux](https://www.electronjs.org/docs/latest/api/browser-window#event-moved-macos-windows). Could you add a timer that will trigger the function like this? I think we can then get rid of the `moved` event altogether!
```ts
  let moveTimer = undefined;
  captureWindow.on("move", (event) => {
    clearTimeout(moveTimer);
    moveTimer = setTimeout(() => {
      checkWindowBounds(captureWindow);
      determineScreenToCapture();
    }, 100);
    updateMain(captureWindow.getPosition(), null);
  });
```

File: src/render.js [hunk 2]
```diff
@@ -46,14 +36,14 @@ async function selectSource(source, display) {
 let currentDisplay = null
 let dispx = 0
 let dispy = 0
-ipcRenderer.on("update-screen-to-capture", async (event, display) => {
-  cons.log(`>> update display: ${display.id}`)
+ipcRenderer.on("update-screen-to-capture",  async (event, { display, sourceId }) => {
+  cons.log(`>> update display: ${display.id}, ${sourceId}`);
   if (!currentDisplay || display.id !== currentDisplay.id) {
```
Comment (mPyKen) [inline src/render.js:41]: I think it would be nice if we moved this condition to `determineScreenToCapture()` since the query for available sources has moved there

**Review by mPyKen — COMMENTED** [review]
Thank you for the PR as well as all the investigation! Could you address the 2 items? Otherwise I will merge it and update the parts by myself!

**Comment by mPyKen** [comment]
Also, I am wondering about the display_id property that don't match - does that happen only on your linux machine? Or on all machines? I tested this on my local (Manjaro Linux) machine and it found the display_id correctly. I wonder if this is hardware (monitor) related or software related

File: src/index.js (hunk 1 above)
Comment (joeskeen) [reply src/index.js:112]: I like it - something like a debounce

**Comment by joeskeen** [comment]
Another thing I noticed today when trying to use this version - at least in Linux Mint the capture window seems to capture the mouse click events, and you can't click or drag through the capture window. I'll want to look into fixing this as well.

**Comment by joeskeen** [comment]
sorry about the close and re-open - 3-year-old wanted to push buttons on my keyboard :facepalm:

**Comment by mPyKen** [comment]
> Also, I am wondering about the display_id property that don't match - does that happen only on your linux machine or on all machines? I tested this on my local (Manjaro Linux) machine and it found the display_id correctly. I wonder if this is hardware (monitor) related or software related

I am using i3, I can confirm clicking through does not really work. It seems to be alternating between letting mouse events through and not. These logs from `xev` are being repeated:
```
...
LeaveNotify event, serial 34, synthetic NO, window 0x7600001,
    root 0x1f4, subw 0x0, time 109828541, (41,519), root:(901,540),
    mode NotifyNormal, detail NotifyNonlinear, same_screen YES,
    focus NO, state 16

EnterNotify event, serial 34, synthetic NO, window 0x7600001,
    root 0x1f4, subw 0x0, time 109828550, (10,522), root:(870,543),
    mode NotifyNormal, detail NotifyNonlinear, same_screen YES,
    focus NO, state 16

KeymapNotify event, serial 34, synthetic NO, window 0x0,
    keys:  244 0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
...
```

whereas it should get MotionNotify events if not trying to go through the capture window:

```
...
MotionNotify event, serial 34, synthetic NO, window 0x3000001,
    root 0x1f4, subw 0x0, time 109966947, (297,651), root:(1157,672),
    state 0x10, is_hint 0, same_screen YES
...
```
